from typing import Annotated, List, TypedDict
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    messages: Annotated[List, add_messages]
    research_data: str  # Data gathered by the Researcher
    draft_report: str   # Report generated by the Writer
    next_step: str      # "Researcher", "Writer", or "FINISH"
